# Generated by Django 5.1.1 on 2024-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.CharField(default='In Stock', max_length=100),
        ),
    ]
