# Generated by Django 5.1.1 on 2024-09-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_out_of_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='out_of_stock',
        ),
    ]
